ORCHESTRATIONS: Persistance - PurgeCsvRecords
NHSISL/ISL.ReIdentification pull request #259
Opened 2024-11-18 10:01 UTC by JParkesAD

CLOSES #AB17124

2024-11-18 16:46 UTC, MichaelOSullivanAnswer commented on ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.PurgeCsvReIdentificationRecordsThatExpired.cs
> +
remove empty line

2024-11-18 16:46 UTC, cjdutoit requested changes

2024-11-18 16:46 UTC, cjdutoit commented on ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
> +
Validate that the `csvReIdentificationConfigurations` is not null.
If this is null, you would look at the int initialising to a value of 0 which will mean immediate expiry.  
I think validate that value is greater than 5

2024-11-18 16:46 UTC, cjdutoit commented on ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
> +            DateTimeOffset expiryDate =
Need validation to ensure `this.csvReIdentificationConfigurations` is not null and then that 
`this.csvReIdentificationConfigurations.ExpireAfterMinutes` has a value greater than 5

2024-11-19 11:36 UTC, JParkesAD commented on ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.PurgeCsvReIdentificationRecordsThatExpired.cs
> +
Fixed

2024-11-19 11:36 UTC, JParkesAD commented on ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
> +
Change pushed

2024-11-19 11:36 UTC, JParkesAD commented on ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
> +            DateTimeOffset expiryDate =
Change pushed

2024-11-20 15:48 UTC, JParkesAD commented on ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.Exceptions.cs
> +                throw await CreateAndLogValidationExceptionAsync(nullCsvReIdentificationConfigurationException);
Change pushed

2024-11-20 15:54 UTC, cjdutoit approved these changes

2024-11-22 09:08 UTC, cjdutoit approved these changes

2024-11-22 09:09 UTC, merged